services:
  php:
    build:
      context: .
    container_name: "behat-min"
    volumes:
      - .:/web
      - "composer_cache:/root/.composer"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"

volumes:
  composer_cache:
    name: raketa_composer_cache